name: Preprocessing Automation

on:
    push: # Workflow otomatis jalan tiap ada push ke repo
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    preprocessing:
        runs-on: ubuntu-latest # VM yang dipakai GitHub Actions

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run preprocessing
              run: |
                  python preprocessing/automate_Shafira-Maulidina.py
